#! /bin/sh

##
# buildrpm
#
# Vega Strike - Space Simulation, Combat and Trading
# Copyright (C) 2001-2026 The Vega Strike Contributors:
# Project creator: Daniel Horn
# Original development team: As listed in the AUTHORS file
# Current development team: Roy Falk, Benjamen R. Meyer, Stephen G. Tuggy
#
# https://github.com/vegastrike/Vega-Strike-Engine-Source
#
# This file is part of Vega Strike.
#
# Vega Strike is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Vega Strike is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Vega Strike.  If not, see <https://www.gnu.org/licenses/>.
#


##
# Attempt to automatically update this directory and build a RPM file
# Must be root
#


#cvs -z3 up -d
#make distclean

cp vegastrike.spec /usr/src/RPM/SPECS/
cp vegastrike.xpm /usr/src/RPM/SOURCES/
# Make tar file
cd ..
tar -zcf vegastrike.tar.gz vegastrike

cp vegastrike.tar.gz /usr/src/RPM/SOURCES/

# Now make RPM
cd /usr/src/RPM/SPECS
rpm -ba vegastrike.spec

echo Hopefully you have just built an RPM file.
