SET(VCPKG_TARGET_ARCHITECTURE x64)
SET(VCPKG_CRT_LINKAGE static)
SET(VCPKG_LIBRARY_LINKAGE static)

LIST(APPEND VCPKG_CMAKE_CONFIGURE_OPTIONS -DBOOST_USE_WINAPI_VERSION=0x0A00 -D_WIN32_WINNT=0x0A00 -DWINVER=0x0A00)

LIST(APPEND VCPKG_CMAKE_CONFIGURE_OPTIONS "-DCMAKE_MAP_IMPORTED_CONFIG_RelWithDebInfo=RelWithDebInfo;Release;Debug;")

IF ("${PORT}" STREQUAL "openal-soft")
    LIST(APPEND VCPKG_CMAKE_CONFIGURE_OPTIONS -DLIBTYPE=STATIC)
ENDIF ()
