##
# gh-actions-pr.yml
#
# Vega Strike - Space Simulation, Combat and Trading
# Copyright (C) 2001-2026 The Vega Strike Contributors:
# Project creator: Daniel Horn
# Original development team: As listed in the AUTHORS file
# Current development team: Roy Falk, Benjamen R. Meyer, Stephen G. Tuggy
#
# https://github.com/vegastrike/Vega-Strike-Engine-Source
#
# This file is part of Vega Strike.
#
# Vega Strike is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Vega Strike is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Vega Strike.  If not, see <https://www.gnu.org/licenses/>.
#
name: 'GH Actions - PR'
permissions:
    contents: read
    pull-requests: read

on: [ pull_request ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    continue-on-error: ${{ matrix.allow_failure }}

    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        include:
          - FROM:     'ubuntu:questing'
            COMPILER: 'gcc'
            preset-name: 'linux-unix-makefiles-pie-disabled-glvnd-RelWithDebInfo'
            allow_failure: false
          - FROM:     'ubuntu:noble'
            COMPILER: 'gcc'
            preset-name: 'linux-unix-makefiles-pie-disabled-glvnd-RelWithDebInfo'
            allow_failure: false
          - FROM:     'ubuntu:noble'
            COMPILER: 'clang'
            preset-name: 'linux-unix-makefiles-pie-disabled-glvnd-RelWithDebInfo'
            allow_failure: false
          - FROM:     'linuxmintd/mint22.2-amd64'
            COMPILER: 'gcc'
            preset-name: 'linux-unix-makefiles-pie-disabled-glvnd-RelWithDebInfo'
            allow_failure: false
          - FROM:     'linuxmintd/mint22-amd64'
            COMPILER: 'clang'
            preset-name: 'linux-unix-makefiles-pie-disabled-glvnd-RelWithDebInfo'
            allow_failure: false
          - FROM:     'debian:trixie'
            COMPILER: 'gcc'
            preset-name: 'linux-unix-makefiles-pie-disabled-glvnd-RelWithDebInfo'
            allow_failure: false
          - FROM:     'debian:bookworm'
            COMPILER: 'clang'
            preset-name: 'linux-unix-makefiles-pie-disabled-glvnd-RelWithDebInfo'
            allow_failure: false
          - FROM:     'fedora:43'
            COMPILER: 'gcc'
            preset-name: 'linux-unix-makefiles-pie-enabled-glvnd-RelWithDebInfo'
            allow_failure: false
          - FROM:     'fedora:42'
            COMPILER: 'gcc'
            preset-name: 'linux-unix-makefiles-pie-enabled-glvnd-RelWithDebInfo'
            allow_failure: false
          - FROM:     'fedora:41'
            COMPILER: 'clang'
            preset-name: 'linux-unix-makefiles-pie-enabled-glvnd-RelWithDebInfo'
            allow_failure: false
          - FROM:     'opensuse/leap:16.0'
            COMPILER: 'gcc'
            preset-name: 'linux-unix-makefiles-pie-enabled-glvnd-RelWithDebInfo'
            allow_failure: false
          - FROM:     'rockylinux/rockylinux:10.1'
            COMPILER: 'gcc'
            preset-name: 'linux-unix-makefiles-pie-enabled-glvnd-RelWithDebInfo'
            allow_failure: false
          - FROM:     'rockylinux/rockylinux:10.0'
            COMPILER: 'gcc'
            preset-name: 'linux-unix-makefiles-pie-enabled-glvnd-RelWithDebInfo'
            allow_failure: false

    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 2
          submodules: false

      # Ensure PRs are built against the PR Head
      # As opposed to the merge commit
      - name: Move to PR HEAD
        run: git checkout ${{ github.event.pull_request.head.sha }}

      - name: Extract short SHA
        shell: bash
        run: |
          echo "SHORT_SHA=`git rev-parse --short ${{ github.event.pull_request.head.sha }}`" >> $GITHUB_ENV
      - name: Test short SHA
        run: |
          echo "${SHORT_SHA}"

      - name: Build and Test
        env:
          FROM:       ${{ matrix.FROM }}
          COMPILER:   ${{ matrix.COMPILER }}
          IS_RELEASE: 0
        run: script/cibuild --preset-name="${{ matrix.preset-name }}"

      - name: Upload test results
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        if: failure()
        with:
          name: test_results_xml
          path: ${{github.workspace}}/test-results/**/*.xml
