name: 'GH Actions - PR'

on: [ pull_request ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: true
      matrix:
        include:
          - FROM:     'ubuntu:jammy'
            COMPILER: 'gcc'
            OpenGL_GL_PREFERENCE: 'LEGACY'
          - FROM:     'ubuntu:jammy'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'LEGACY'
          - FROM:     'ubuntu:jammy'
            COMPILER: 'gcc'
            OpenGL_GL_PREFERENCE: 'GLVND'
          - FROM:     'ubuntu:jammy'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
          - FROM:     'ubuntu:impish'
            COMPILER: 'gcc'
            OpenGL_GL_PREFERENCE: 'LEGACY'
          - FROM:     'ubuntu:impish'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'LEGACY'
          - FROM:     'ubuntu:impish'
            COMPILER: 'gcc'
            OpenGL_GL_PREFERENCE: 'GLVND'
          - FROM:     'ubuntu:impish'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
          - FROM:     'ubuntu:focal'
            COMPILER: 'gcc'
            OpenGL_GL_PREFERENCE: 'LEGACY'
          - FROM:     'ubuntu:focal'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'LEGACY'
          - FROM:     'ubuntu:focal'
            COMPILER: 'gcc'
            OpenGL_GL_PREFERENCE: 'GLVND'
          - FROM:     'ubuntu:focal'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
          - FROM:     'ubuntu:bionic'
            COMPILER: 'gcc'
            OpenGL_GL_PREFERENCE: 'LEGACY'
          - FROM:     'ubuntu:bionic'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
          - FROM:     'ubuntu:bionic'
            COMPILER: 'gcc'
            OpenGL_GL_PREFERENCE: 'GLVND'
          - FROM:     'ubuntu:bionic'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'LEGACY'
          - FROM:     'linuxmintd/mint20-amd64'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'LEGACY'
          - FROM:     'linuxmintd/mint20-amd64'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
          - FROM:     'debian:bullseye'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'LEGACY'
          - FROM:     'debian:bullseye'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
          - FROM:     'debian:buster'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'LEGACY'
          - FROM:     'debian:buster'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
          - FROM:     'opensuse/leap'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'LEGACY'
          - FROM:     'opensuse/leap'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
          - FROM:     'fedora:36'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'LEGACY'
          - FROM:     'fedora:36'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
          - FROM:     'fedora:35'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'LEGACY'
          - FROM:     'fedora:35'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
          - FROM:     'rockylinux/rockylinux'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'LEGACY'
          - FROM:     'rockylinux/rockylinux'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
          - FROM:     'manjarolinux/base'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'LEGACY'
          - FROM:     'manjarolinux/base'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'

    steps:
    - name: Checkout repository
      uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 #v3.1.0
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 2
        submodules: false

    # Ensure PRs are built against the PR Head
    # As opposed to the merge commit
    - name: Move to PR HEAD
      run: git checkout ${{ github.event.pull_request.head.sha }}

    - name: Extract short SHA
      shell: bash
      run: |
        echo "SHORT_SHA=`git rev-parse --short ${{ github.event.pull_request.head.sha }}`" >> $GITHUB_ENV
    - name: Test short SHA
      run: |
        echo "${SHORT_SHA}"

    - name: Build and Test
      env:
        FROM:       ${{ matrix.FROM }}
        COMPILER:   ${{ matrix.COMPILER }}
        FLAGS:      '-DOpenGL_GL_PREFERENCE=${{ matrix.OpenGL_GL_PREFERENCE }}'
        MY_OS_NAME: linux
        IS_RELEASE: 0
      run: script/cibuild $FLAGS

    # This is run from inside the Docker container, by script/docker-entrypoint.sh
    # - name: Test
    #   working-directory: ${{github.workspace}}/build
    #   env:
    #     GTEST_OUTPUT: xml
    #     GTEST_COLOR: 1
    #   run: ctest -V

    - name: Upload test results
      uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb #v3.1.1
      if: failure()
      with:
        name: test_results_xml
        path: ${{github.workspace}}/test-results/**/*.xml
