name: 'GH Actions - Release'

on:
  release:
    types:
      - created
      - edited

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - FROM:     'ubuntu:impish'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'LEGACY'
            ARTIFACT_EXT: 'deb'
          - FROM:     'ubuntu:impish'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ARTIFACT_EXT: 'deb'
          - FROM:     'ubuntu:focal'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'LEGACY'
            ARTIFACT_EXT: 'deb'
          - FROM:     'ubuntu:focal'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ARTIFACT_EXT: 'deb'
          # Source tarballs only
          - FROM:     'ubuntu:focal'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ARTIFACT_EXT: 'tar.[xb]z*'
          - FROM:     'ubuntu:bionic'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'LEGACY'
            ARTIFACT_EXT: 'deb'
          - FROM:     'ubuntu:bionic'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ARTIFACT_EXT: 'deb'
          - FROM:     'linuxmintd/mint20-amd64'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'LEGACY'
            ARTIFACT_EXT: 'deb'
          - FROM:     'linuxmintd/mint20-amd64'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ARTIFACT_EXT: 'deb'
          - FROM:     'debian:bullseye'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'LEGACY'
            ARTIFACT_EXT: 'deb'
          - FROM:     'debian:bullseye'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ARTIFACT_EXT: 'deb'
          - FROM:     'debian:buster'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'LEGACY'
            ARTIFACT_EXT: 'deb'
          - FROM:     'debian:buster'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ARTIFACT_EXT: 'deb'
          - FROM:     'opensuse/leap'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'LEGACY'
            ARTIFACT_EXT: 'rpm'
          - FROM:     'opensuse/leap'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ARTIFACT_EXT: 'rpm'
          - FROM:     'fedora:35'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'LEGACY'
            ARTIFACT_EXT: 'rpm'
          - FROM:     'fedora:35'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ARTIFACT_EXT: 'rpm'
          - FROM:     'fedora:34'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'LEGACY'
            ARTIFACT_EXT: 'rpm'
          - FROM:     'fedora:34'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ARTIFACT_EXT: 'rpm'
          - FROM:     'rockylinux/rockylinux'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'LEGACY'
            ARTIFACT_EXT: 'rpm'
          - FROM:     'rockylinux/rockylinux'
            COMPILER: 'clang'
            OpenGL_GL_PREFERENCE: 'GLVND'
            ARTIFACT_EXT: 'rpm'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 2
        submodules: false

    # where in a pull request we want to move to the head of the PR and not be at the
    # merge commit; here we want to be at the HEAD of the ref

    - name: Extract tag name and short SHA
      shell: bash
      run: |
        echo "TAG_NAME=$(echo ${GITHUB_REF#refs/tags/} | sed 's/\//_/g')" >> $GITHUB_ENV
        echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV
    - name: Test tag name and short SHA
      run: |
        echo "${TAG_NAME}"
        echo "${SHORT_SHA}"
    - name: Run CI
      env:
        FROM:       ${{ matrix.FROM }}
        COMPILER:   ${{ matrix.COMPILER }}
        FLAGS:      '-DOpenGL_GL_PREFERENCE=${{ matrix.OpenGL_GL_PREFERENCE }}'
        MY_OS_NAME: linux
        IS_RELEASE: 1
      run: script/cibuild $FLAGS
    - name: Upload the artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ARTIFACT_EXT: ${{ matrix.ARTIFACT_EXT }}
      with:
        args: "packages/*.${{ matrix.ARTIFACT_EXT }}"
