name: 'GH Actions - Release'

on:
  release:
    types:
      - created
      - edited

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    continue-on-error: true

    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        include:
          - FROM:     'ubuntu:noble'
            COMPILER: 'clang'
            preset-name: 'linux-unix-makefiles-pie-disabled-glvnd-RelWithDebInfo'
            ARTIFACT_EXT: 'deb'
          # Source tarballs only
          - FROM:     'ubuntu:noble'
            COMPILER: 'clang'
            preset-name: 'linux-unix-makefiles-pie-disabled-glvnd-RelWithDebInfo'
            ARTIFACT_EXT: 'tar.[xb]z*'
          - FROM:     'linuxmintd/mint22-amd64'
            COMPILER: 'clang'
            preset-name: 'linux-unix-makefiles-pie-disabled-glvnd-RelWithDebInfo'
            ARTIFACT_EXT: 'deb'
          - FROM:     'debian:bookworm'
            COMPILER: 'clang'
            preset-name: 'linux-unix-makefiles-pie-disabled-glvnd-RelWithDebInfo'
            ARTIFACT_EXT: 'deb'
          - FROM:     'fedora:41'
            COMPILER: 'clang'
            preset-name: 'linux-unix-makefiles-pie-enabled-glvnd-RelWithDebInfo'
            ARTIFACT_EXT: 'rpm'
          - FROM:     'fedora:40'
            COMPILER: 'clang'
            preset-name: 'linux-unix-makefiles-pie-enabled-glvnd-RelWithDebInfo'
            ARTIFACT_EXT: 'rpm'

    steps:
      - name: Check out repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 2
          submodules: false

      - name: Extract tag name and short SHA
        shell: bash
        run: |
          echo "TAG_NAME=$(echo ${GITHUB_REF#refs/tags/} | sed 's/\//_/g')" >> $GITHUB_ENV
          echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV
      - name: Test tag name and short SHA
        run: |
          echo "${TAG_NAME}"
          echo "${SHORT_SHA}"
      - name: Run CI
        env:
          FROM:       ${{ matrix.FROM }}
          COMPILER:   ${{ matrix.COMPILER }}
          MY_OS_NAME: linux
          IS_RELEASE: 1
        run: script/cibuild --preset-name=${{ matrix.preset-name }}
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@44887b225ceca96efd8a912d39c09ad70312af31 # master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARTIFACT_EXT: ${{ matrix.ARTIFACT_EXT }}
        with:
          args: "packages/*.${{ matrix.ARTIFACT_EXT }}"
