name: 'MacOS-Release'
permissions:
    contents: write
    pull-requests: read

on:
  release:
    types:
      - created
      - edited

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    continue-on-error: true

    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macOS-13
            build-type: RelWithDebInfo
            preset-name: macos-pie-enabled-RelWithDebInfo
            python-version: 3.13.5

    steps:
      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        id: vega-py-setup
        with:
          python-version: ${{ matrix.python-version }}
          update-environment: false

      - name: Install dependencies using homebrew
        run: brew install boost-python3 gtk+3 gtkglext sdl libvorbis

      - name: Install the latest version of Bash so we can rely on it
        run: brew install bash

      - name: Check out repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 2
          submodules: false

      - name: Bootstrap MacOS
        run: script/bootstrap-mac.sh

      - name: Extract tag name and short SHA
        shell: bash
        run: |
          echo "TAG_NAME=$(echo ${GITHUB_REF#refs/tags/} | sed 's/\//_/g')" >> $GITHUB_ENV
          echo "SHORT_SHA=`git rev-parse --short HEAD`" >> $GITHUB_ENV
      - name: Test tag name and short SHA
        run: |
          echo "${TAG_NAME}"
          echo "${SHORT_SHA}"

      - name: Build it
        env:
          MY_OS_NAME: macos
          COMPILER:   ${{ matrix.compiler }}
          Python3_ROOT_DIR: ${{ steps.vega-py-setup.outputs.python-path }}
          Python_ROOT_DIR: ${{ steps.vega-py-setup.outputs.python-path }}
          pythonLocation: ${{ steps.vega-py-setup.outputs.python-path }}
          PYTHONHOME: ""
          PYTHONPATH: ""
          IS_RELEASE: 1
        run: script/cibuild --preset-name=${{ matrix.preset-name }}

      - name: Package it
        working-directory: ${{github.workspace}}
        run: cpack -V --preset-name="package-${{ matrix.preset-name }}"

      - name: Upload the artifacts
        uses: softprops/action-gh-release@c062e08bd532815e2082a85e87e3ef29c3e6d191 # v2.0.8
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: "packages/*.*"
